In [33]:
import os
print(os.getcwd())
os.chdir('/home/user1/MXY/EHRScore') # Change to the project directory

/home/user1/MXY/EHRScore

In [34]:
import pandas as pd

# read formatted mimic3 data
os.makedirs("data/mimic3/preprocessed", exist_ok=True)
data_path = "data/mimic3/format_mimic3_anonymized.csv"
mimic3_df = pd.read_csv(data_path)
mimic3_df

,PatientID,VisitID,RecordTime,RecordTimestamp,AdmissionTime,DischargeTime,Outcome,LOS,Readmission,Sex,...,Temperature,Oxygen saturation,Fraction inspired oxygen,Glucose,PH,Conditions_ICD9,Conditions_Long,Medications,Procedures_ICD9,Procedures_Long
0,10001,1,1,2146-08-05 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,37.17,NaN,NaN,NaN,NaN,56212;42732;5559;9982;2851;5601;2762;45342;276...,Diverticulosis of colon with hemorrhage;Atrial...,LR;LR;0.9% Sodium Chloride;0.9% Sodium Chlorid...,4582;3979;4593;4195;8847;9915;9977,Open total intra-abdominal colectomy;Other end...
1,10001,1,2,2146-08-06 01:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,36.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10001,1,3,2146-08-06 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,36.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001,1,4,2146-08-07 01:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,37.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10001,1,5,2146-08-07 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,37.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224447,56445,1,12,2156-06-15 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,36.94,NaN,NaN,111.0,NaN,NaN,NaN,NaN,NaN,NaN
1224448,56445,1,13,2156-06-15 15:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,37.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1224449,56445,1,14,2156-06-16 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,36.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1224450,56445,1,15,2156-06-16 15:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,37.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1224451,56445,1,16,2156-06-17 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
# Filter the data to include only patients with ≥10 records.
filtered_df = mimic3_df.groupby('PatientID').filter(lambda x: len(x) >= 10)

# Take the first 48 records for each patient.
mimic3_filtered_df = filtered_df.groupby(['PatientID', 'VisitID']).head(48)

mimic3_filtered_df

,PatientID,VisitID,RecordTime,RecordTimestamp,AdmissionTime,DischargeTime,Outcome,LOS,Readmission,Sex,...,Temperature,Oxygen saturation,Fraction inspired oxygen,Glucose,PH,Conditions_ICD9,Conditions_Long,Medications,Procedures_ICD9,Procedures_Long
0,10001,1,1,2146-08-05 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,37.17,NaN,NaN,NaN,NaN,56212;42732;5559;9982;2851;5601;2762;45342;276...,Diverticulosis of colon with hemorrhage;Atrial...,LR;LR;0.9% Sodium Chloride;0.9% Sodium Chlorid...,4582;3979;4593;4195;8847;9915;9977,Open total intra-abdominal colectomy;Other end...
1,10001,1,2,2146-08-06 01:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,36.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10001,1,3,2146-08-06 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,36.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001,1,4,2146-08-07 01:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,37.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10001,1,5,2146-08-07 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,37.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224447,56445,1,12,2156-06-15 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,36.94,NaN,NaN,111.0,NaN,NaN,NaN,NaN,NaN,NaN
1224448,56445,1,13,2156-06-15 15:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,37.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1224449,56445,1,14,2156-06-16 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,36.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1224450,56445,1,15,2156-06-16 15:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,37.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1224451,56445,1,16,2156-06-17 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
# Perform LOCF(Last Observation Carried Forward) imputation
exclude_cols = [
    'Conditions_ICD9',
    'Conditions_Long',
    'Medications',
    'Procedures_ICD9',
    'Procedures_Long'
]

cols_to_impute = [col for col in mimic3_filtered_df.columns if col not in exclude_cols]

# locf
locf_imputed_df = mimic3_filtered_df.copy()
locf_imputed_df[cols_to_impute] = locf_imputed_df.groupby(['PatientID', 'VisitID'])[cols_to_impute].ffill()

# nocb
nocb_imputed_df = locf_imputed_df.copy()
nocb_imputed_df[cols_to_impute] = nocb_imputed_df.groupby(['PatientID', 'VisitID'])[cols_to_impute].bfill()

nocb_imputed_df

,PatientID,VisitID,RecordTime,RecordTimestamp,AdmissionTime,DischargeTime,Outcome,LOS,Readmission,Sex,...,Temperature,Oxygen saturation,Fraction inspired oxygen,Glucose,PH,Conditions_ICD9,Conditions_Long,Medications,Procedures_ICD9,Procedures_Long
0,10001,1,1,2146-08-05 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,37.17,98.0,NaN,129.0,7.41,56212;42732;5559;9982;2851;5601;2762;45342;276...,Diverticulosis of colon with hemorrhage;Atrial...,LR;LR;0.9% Sodium Chloride;0.9% Sodium Chlorid...,4582;3979;4593;4195;8847;9915;9977,Open total intra-abdominal colectomy;Other end...
1,10001,1,2,2146-08-06 01:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,36.72,98.0,NaN,129.0,7.41,NaN,NaN,NaN,NaN,NaN
2,10001,1,3,2146-08-06 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,36.22,98.0,NaN,129.0,7.41,NaN,NaN,NaN,NaN,NaN
3,10001,1,4,2146-08-07 01:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,37.06,98.0,NaN,129.0,7.41,NaN,NaN,NaN,NaN,NaN
4,10001,1,5,2146-08-07 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,37.28,98.0,NaN,129.0,7.41,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224447,56445,1,12,2156-06-15 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,36.94,87.0,NaN,111.0,7.46,NaN,NaN,NaN,NaN,NaN
1224448,56445,1,13,2156-06-15 15:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,37.00,87.0,NaN,111.0,7.46,NaN,NaN,NaN,NaN,NaN
1224449,56445,1,14,2156-06-16 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,36.83,87.0,NaN,111.0,7.46,NaN,NaN,NaN,NaN,NaN
1224450,56445,1,15,2156-06-16 15:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,37.00,87.0,NaN,111.0,7.46,NaN,NaN,NaN,NaN,NaN
1224451,56445,1,16,2156-06-17 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,37.00,87.0,NaN,111.0,7.46,NaN,NaN,NaN,NaN,NaN

In [37]:
# Save the time-series data for subsequent statistical analysis
timeseries_df = nocb_imputed_df[cols_to_impute]
timeseries_df.to_csv("data/mimic3/preprocessed/timeseries_mimic3.csv", index=False)
timeseries_df

,PatientID,VisitID,RecordTime,RecordTimestamp,AdmissionTime,DischargeTime,Outcome,LOS,Readmission,Sex,...,Diastolic blood pressure,Systolic blood pressure,Mean blood pressure,Heart Rate,Respiratory rate,Temperature,Oxygen saturation,Fraction inspired oxygen,Glucose,PH
0,10001,1,1,2146-08-05 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,101.0,205.0,141.0,107.0,24.0,37.17,98.0,NaN,129.0,7.41
1,10001,1,2,2146-08-06 01:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,101.0,205.0,141.0,104.0,20.0,36.72,98.0,NaN,129.0,7.41
2,10001,1,3,2146-08-06 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,101.0,205.0,141.0,112.0,23.0,36.22,98.0,NaN,129.0,7.41
3,10001,1,4,2146-08-07 01:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,101.0,205.0,141.0,128.0,22.0,37.06,98.0,NaN,129.0,7.41
4,10001,1,5,2146-08-07 13:57:00,2146-08-05 13:57:00,2146-08-31 15:59:00,0,26.08,0,1,...,101.0,205.0,141.0,113.0,24.0,37.28,98.0,NaN,129.0,7.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224447,56445,1,12,2156-06-15 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,97.0,150.0,347.0,78.0,26.0,36.94,87.0,NaN,111.0,7.46
1224448,56445,1,13,2156-06-15 15:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,97.0,150.0,347.0,75.0,24.0,37.00,87.0,NaN,111.0,7.46
1224449,56445,1,14,2156-06-16 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,97.0,150.0,347.0,73.0,25.0,36.83,87.0,NaN,111.0,7.46
1224450,56445,1,15,2156-06-16 15:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,97.0,150.0,347.0,77.0,25.0,37.00,87.0,NaN,111.0,7.46
1224451,56445,1,16,2156-06-17 03:49:00,2156-06-09 15:49:00,2156-06-17 15:20:00,0,7.98,0,1,...,97.0,150.0,347.0,92.0,31.0,37.00,87.0,NaN,111.0,7.46

In [38]:
# Extract the patient's conditions, medications, and procedures to CMPs.csv
clinical_cols = [
    'PatientID', 'VisitID',
    'Conditions_ICD9', 'Conditions_Long',
    'Medications',
    'Procedures_ICD9', 'Procedures_Long'
]
cmps_df = nocb_imputed_df.groupby(['PatientID', 'VisitID']).first().reset_index()[clinical_cols]

cmps_df.to_csv("data/mimic3/preprocessed/CMPs_mimic3.csv", index=False)
cmps_df

,PatientID,VisitID,Conditions_ICD9,Conditions_Long,Medications,Procedures_ICD9,Procedures_Long
0,10001,1,56212;42732;5559;9982;2851;5601;2762;45342;276...,Diverticulosis of colon with hemorrhage;Atrial...,LR;LR;0.9% Sodium Chloride;0.9% Sodium Chlorid...,4582;3979;4593;4195;8847;9915;9977,Open total intra-abdominal colectomy;Other end...
1,10004,1,V3000;7790;77083;V053;V5869,"Single liveborn, born in hospital, delivered w...",NEO*PO*Phenobarbital;NEO*IV*Acyclovir;Syringe ...,0331;9955;9543,Spinal tap;Prophylactic administration of vacc...
2,10005,1,V3000;7756;V290;V053;V502;7963;7706,"Single liveborn, born in hospital, delivered w...",NEO*IV*Ampicillin Sodium;Syringe (Neonatal) *D...,9955;640,Prophylactic administration of vaccine against...
3,10006,1,43491;34292;4019;25051;36201;2720;3051,"Cerebral artery occlusion, unspecified with ce...",Insulin;Fentanyl Citrate;Zolpidem Tartrate;Ins...,9671;3893;8872,Continuous invasive mechanical ventilation for...
4,10007,1,5070;1985;4660;185;79902;28522,Pneumonitis due to inhalation of food or vomit...,Acetaminophen;Vancomycin;CefePIME;0.9% Sodium ...,9904,Transfusion of packed cells
...,...,...,...,...,...,...,...
44341,56441,2,431;452;34982;2762;2761;5990;1550;4561;514;401...,Intracerebral hemorrhage;Portal vein thrombosi...,Omeprazole;0.9% Sodium Chloride;0.9% Sodium Ch...,0139;3897,Other incision of brain;Central venous cathete...
44342,56442,1,44101;5119;2859;515;27801;4414;4019;2749;42731...,"Dissection of aorta, thoracic;Unspecified pleu...",Metoprolol Tartrate;Metoprolol Tartrate;Pantop...,3973;3922;8847;8844,Endovascular implantation of graft in thoracic...
44343,56442,2,9961;5845;570;51851;78559;99812;99811;99731;72...,Mechanical complication of other vascular devi...,Sterile Water;Furosemide;Ciprofloxacin HCl;Met...,311;9672;3806;3808;5412;5412;5462;3174;4311;33...,Temporary tracheostomy;Continuous invasive mec...
44344,56443,1,5750;5849;486;5119;42732;7907;42731;25000;0413...,"Acute cholecystitis;Acute kidney failure, unsp...",Magnesium Sulfate;Magnesium Sulfate;Magnesium ...,5101;3491,Percutaneous aspiration of gallbladder;Thorace...
44345,56445,1,41401;5849;5119;5180;4142;53085;53081;5859;272...,Coronary atherosclerosis of native coronary ar...,Docusate Sodium (Liquid);Morphine Sulfate;Morp...,3615;3613;3961;8873;3324;3893;3404;8627,Single internal mammary-coronary artery bypass...