In [8]:
import os
print(os.getcwd())
os.chdir('/home/user1/MXY/EHRScore') # Change to the project directory

/home/user1/MXY/EHRScore

In [9]:
import pandas as pd

# read formatted mimic4 data
os.makedirs("data/mimic4/preprocessed", exist_ok=True)
data_path = "data/mimic4/format_mimic4_anonymized.csv"
mimic4_df = pd.read_csv(data_path)
mimic4_df

,PatientID,VisitID,RecordTime,RecordTimestamp,AdmissionTime,DischargeTime,Outcome,LOS,Readmission,Sex,...,Temperature,Oxygen saturation,Fraction inspired oxygen,Glucose,PH,Conditions_ICD9,Conditions_Long,Medications,Procedures_ICD9,Procedures_Long
0,10001,1,1,2111-06-04 22:33:00,2111-06-04 22:33:00,2111-06-07 20:59:00,0,2.93,0,0,...,NaN,NaN,NaN,NaN,NaN,2809;2731;4019;2113;53560;5533;56210;4240;V103,"Iron deficiency anemia, unspecified;Monoclonal...",Ferric Gluconate;Pneumococcal Vac Polyvalent;S...,4516;4542,Esophagogastroduodenoscopy [EGD] with closed b...
1,10001,1,2,2111-06-05 10:33:00,2111-06-04 22:33:00,2111-06-07 20:59:00,0,2.93,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10001,1,3,2111-06-05 22:33:00,2111-06-04 22:33:00,2111-06-07 20:59:00,0,2.93,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001,1,4,2111-06-06 10:33:00,2111-06-04 22:33:00,2111-06-07 20:59:00,0,2.93,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10001,1,5,2111-06-06 22:33:00,2111-06-04 22:33:00,2111-06-07 20:59:00,0,2.93,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4082066,190677,3,15,2142-02-11 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,36.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4082067,190677,3,16,2142-02-12 06:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,36.83,98.0,NaN,NaN,7.34,NaN,NaN,NaN,NaN,NaN
4082068,190677,3,17,2142-02-12 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,35.40,96.0,NaN,NaN,7.23,NaN,NaN,NaN,NaN,NaN
4082069,190677,3,18,2142-02-13 06:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,35.70,97.0,NaN,75.0,7.23,NaN,NaN,NaN,NaN,NaN
4082070,190677,3,19,2142-02-13 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Filter the data to include only patients with ≥10 records.
filtered_df = mimic4_df.groupby('PatientID').filter(lambda x: len(x) >= 10)

# Take the first 48 records for each patient.
mimic4_filtered_df = filtered_df.groupby(['PatientID', 'VisitID']).head(48)

mimic4_filtered_df

,PatientID,VisitID,RecordTime,RecordTimestamp,AdmissionTime,DischargeTime,Outcome,LOS,Readmission,Sex,...,Temperature,Oxygen saturation,Fraction inspired oxygen,Glucose,PH,Conditions_ICD9,Conditions_Long,Medications,Procedures_ICD9,Procedures_Long
6,10002,1,1,2122-01-19 07:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,71595;2851;4580;2724;V1272,"Osteoarthrosis, unspecified whether generalize...",0.9% Sodium Chloride;0.9% Sodium Chloride;Mult...,8151,Total hip replacement
7,10002,1,2,2122-01-19 19:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10002,1,3,2122-01-20 07:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10002,1,4,2122-01-20 19:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10002,1,5,2122-01-21 07:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4082066,190677,3,15,2142-02-11 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,36.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4082067,190677,3,16,2142-02-12 06:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,36.83,98.0,NaN,NaN,7.34,NaN,NaN,NaN,NaN,NaN
4082068,190677,3,17,2142-02-12 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,35.40,96.0,NaN,NaN,7.23,NaN,NaN,NaN,NaN,NaN
4082069,190677,3,18,2142-02-13 06:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,35.70,97.0,NaN,75.0,7.23,NaN,NaN,NaN,NaN,NaN
4082070,190677,3,19,2142-02-13 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Perform LOCF(Last Observation Carried Forward) imputation
exclude_cols = [
    'Conditions_ICD9',
    'Conditions_Long',
    'Medications',
    'Procedures_ICD9',
    'Procedures_Long'
]

cols_to_impute = [col for col in mimic4_filtered_df.columns if col not in exclude_cols]

# locf
locf_imputed_df = mimic4_filtered_df.copy()
locf_imputed_df[cols_to_impute] = locf_imputed_df.groupby(['PatientID', 'VisitID'])[cols_to_impute].ffill()

# nocb
nocb_imputed_df = locf_imputed_df.copy()
nocb_imputed_df[cols_to_impute] = nocb_imputed_df.groupby(['PatientID', 'VisitID'])[cols_to_impute].bfill()

nocb_imputed_df

,PatientID,VisitID,RecordTime,RecordTimestamp,AdmissionTime,DischargeTime,Outcome,LOS,Readmission,Sex,...,Temperature,Oxygen saturation,Fraction inspired oxygen,Glucose,PH,Conditions_ICD9,Conditions_Long,Medications,Procedures_ICD9,Procedures_Long
6,10002,1,1,2122-01-19 07:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,71595;2851;4580;2724;V1272,"Osteoarthrosis, unspecified whether generalize...",0.9% Sodium Chloride;0.9% Sodium Chloride;Mult...,8151,Total hip replacement
7,10002,1,2,2122-01-19 19:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10002,1,3,2122-01-20 07:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10002,1,4,2122-01-20 19:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10002,1,5,2122-01-21 07:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4082066,190677,3,15,2142-02-11 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,36.89,98.0,NaN,128.0,7.41,NaN,NaN,NaN,NaN,NaN
4082067,190677,3,16,2142-02-12 06:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,36.83,98.0,NaN,128.0,7.34,NaN,NaN,NaN,NaN,NaN
4082068,190677,3,17,2142-02-12 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,35.40,96.0,NaN,128.0,7.23,NaN,NaN,NaN,NaN,NaN
4082069,190677,3,18,2142-02-13 06:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,35.70,97.0,NaN,75.0,7.23,NaN,NaN,NaN,NaN,NaN
4082070,190677,3,19,2142-02-13 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,35.70,97.0,NaN,75.0,7.23,NaN,NaN,NaN,NaN,NaN

In [12]:
# Save the time-series data for subsequent statistical analysis
timeseries_df = nocb_imputed_df[cols_to_impute]
timeseries_df.to_csv("data/mimic4/preprocessed/timeseries_mimic4.csv", index=False)
timeseries_df

,PatientID,VisitID,RecordTime,RecordTimestamp,AdmissionTime,DischargeTime,Outcome,LOS,Readmission,Sex,...,Diastolic blood pressure,Systolic blood pressure,Mean blood pressure,Heart Rate,Respiratory rate,Temperature,Oxygen saturation,Fraction inspired oxygen,Glucose,PH
6,10002,1,1,2122-01-19 07:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,10002,1,2,2122-01-19 19:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10002,1,3,2122-01-20 07:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10002,1,4,2122-01-20 19:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10002,1,5,2122-01-21 07:15:00,2122-01-19 07:15:00,2122-01-24 12:10:00,0,5.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4082066,190677,3,15,2142-02-11 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,53.0,80.0,64.0,120.0,26.0,36.89,98.0,NaN,128.0,7.41
4082067,190677,3,16,2142-02-12 06:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,60.0,101.0,78.0,118.0,26.0,36.83,98.0,NaN,128.0,7.34
4082068,190677,3,17,2142-02-12 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,53.0,93.0,69.0,125.0,20.0,35.40,96.0,NaN,128.0,7.23
4082069,190677,3,18,2142-02-13 06:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,50.0,87.0,64.0,124.0,21.0,35.70,97.0,NaN,75.0,7.23
4082070,190677,3,19,2142-02-13 18:26:00,2142-02-04 18:26:00,2142-02-13 19:36:00,1,9.05,0,1,...,40.0,66.0,51.0,118.0,21.0,35.70,97.0,NaN,75.0,7.23

In [13]:
# Extract the patient's conditions, medications, and procedures to CMPs.csv
clinical_cols = [
    'PatientID', 'VisitID',
    'Conditions_ICD9', 'Conditions_Long',
    'Medications',
    'Procedures_ICD9', 'Procedures_Long'
]
cmps_df = nocb_imputed_df.groupby(['PatientID', 'VisitID']).first().reset_index()[clinical_cols]

cmps_df.to_csv("data/mimic4/preprocessed/CMPs_mimic4.csv", index=False)
cmps_df

,PatientID,VisitID,Conditions_ICD9,Conditions_Long,Medications,Procedures_ICD9,Procedures_Long
0,10002,1,71595;2851;4580;2724;V1272,"Osteoarthrosis, unspecified whether generalize...",0.9% Sodium Chloride;0.9% Sodium Chloride;Mult...,8151,Total hip replacement
1,10003,1,None,None,Omeprazole;Furosemide;Bisacodyl;Furosemide;Bis...,None,None
2,10003,2,None,None,Finasteride;Tolterodine;Aspirin;ClonazePAM;Pol...,None,None
3,10003,3,None,None,None,None,None
4,10003,4,None,None,Ipratropium-Albuterol Neb;Dorzolamide 2%/Timol...,None,None
...,...,...,...,...,...,...,...
327923,190673,6,None,None,Insulin;Insulin;Lidocaine Jelly 2% (Glydo);Met...,None,None
327924,190674,1,5070;5990;3320;2731;04104;42731;496;3331;48283...,Pneumonitis due to inhalation of food or vomit...,Influenza Vaccine Quadrivalent;Potassium Chl 2...,None,None
327925,190677,1,44629;452;42833;78959;5180;5849;70719;5728;571...,Other specified hypersensitivity angiitis;Port...,Furosemide;Glucagon;Metoprolol Tartrate;Insuli...,8611;3723;8853;8856,Closed biopsy of skin and subcutaneous tissue;...
327926,190677,2,0389;78552;5722;2869;2639;44629;70710;5849;276...,Unspecified septicemia;Septic shock;Hepatic en...,Insulin;Lactulose;Aspirin;Lidocaine Jelly 2% (...,3897,Central venous catheter placement with guidance
327927,190677,3,8208;570;5845;2866;53140;0389;99592;78552;4283...,Closed fracture of unspecified part of neck of...,Spironolactone;0.9% Sodium Chloride;Enoxaparin...,8152;9671;9604;4443;3995;3893;3897;8964,Partial hip replacement;Continuous invasive me...